db:
  image: mongo:latest
  command: --smallfiles
  ports:
    - 27017
app:
  image: node:latest
  working_dir: /app
  command: bash -c "npm install && node app.js"
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - db

